version: '3.4'
networks:
  backend:
services:
    traineedb:
        container_name: trainee-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=apple@123#
        networks:
            - backend
        ports:
            - 8001:1433
    sampledotnetcoreservice:
        image: ${DOCKER_REGISTRY-}sampledotnetcoreservice
        build:
          context: .
          dockerfile: SampleDotnetCoreService/Dockerfile
        networks:
            - backend
        ports:
            - 8002:1433
        depends_on: 
            - traineedb
        environment:
            - DB_HOST =trainee-db
            - DB_NAME =trainee
            - DB_PWD =apple@123#